---
num_of_slaves: 1
prefix_ip_addr: 174.10.100.
tag_version: 6
stable_contrail_ansible_sha: 47a025d8bbef129baf4455fe69ad8cc5d8ceb2eb
memory: 16384
cpus: 8
network: private_network
controller_hostname: controller
builder_hostname: builder
slave_hostname: slave
VAGRANTFILE_API_VERSION: 2
box: centos/7
cntr: 1
provider: virtualbox
