---
vms:
  num_of_slaves: 2
  prefix_ip_addr: 173.10.100.
  tag_version: 6
  stable_contrail_ansible_sha: 47a025d8bbef129baf4455fe69ad8cc5d8ceb2eb
  box: centos/7
  #use your server IP address and marathon port in url
  url: http://10.84.23.35:9990/v2/apps/
mesos:
  include: true
port:
  http: 80
  contrail: 8080
  contrail_json: 8082
  contrail_introspect: 8083
  contrail_http: 8143
  marathon: 8880
  mesos_master: 8881
